export type Status = "live" | "pending" | "not-built";
export type LaneId =
  | "recruiting"
  | "ingest"
  | "counselling"
  | "admissions"
  | "capacity"
  | "funding"
  | "student"
  | "platform"
  | "backlog";

export type RoleId =
  | "admissions"
  | "counsellor"
  | "agent"
  | "finance"
  | "student"
  | "admin";

export type Capability = {
  id: number;
  title: string;
  description: string;
  row: string;
  date: "11 Sep" | null;
  origin: boolean;
  noTake: boolean;
  status: Status;
  blocker: string | null;
  lane: LaneId;
  roles: RoleId[];
  x: number;
  y: number;
  w: number;
  h: number;
};

export type Edge = {
  from: number;
  to: number;
  label: string | null;
};

export type Journey = {
  id: string;
  label: string;
  blurb: string;
  nodes: number[];
};

export type Lane = {
  id: LaneId;
  label: string;
  blurb: string;
};

export const LANES: Lane[] = [
  { id: "recruiting", label: "Recruiting", blurb: "Agents, tracked links, referrals, commission chain." },
  { id: "ingest", label: "Lead ingest", blurb: "Every source collapses to one record, then the queue." },
  { id: "counselling", label: "Counselling", blurb: "Slots, calendar, two session states, outcome." },
  { id: "admissions", label: "Admissions", blurb: "Pipeline, documents, gates, packet, enrol." },
  { id: "capacity", label: "Capacity & placement", blurb: "Batch fill, overflow, partner map, rooms." },
  { id: "funding", label: "Funding & pay", blurb: "Funded vs self-pay, ledger, two commissions, BDM, payroll." },
  { id: "student", label: "Student access", blurb: "Remote enrol, checklist, login, mailbox, portal." },
  { id: "platform", label: "Platform", blurb: "Brand, roles, campuses, audit, SSO, reporting." },
  { id: "backlog", label: "Not in this build", blurb: "Chat, Teams, import, retention, structured export." },
];

export const ROLES: { id: RoleId; label: string }[] = [
  { id: "admissions", label: "Admissions" },
  { id: "counsellor", label: "Counsellor" },
  { id: "agent", label: "Agent" },
  { id: "finance", label: "Finance" },
  { id: "student", label: "Student" },
  { id: "admin", label: "Admin" },
];

export const CAPABILITIES: Capability[] = [
  {
    id: 1,
    title: "Agent is a consulting firm or an individual",
    description: "An agent is either a consulting firm or an individual recruiter. The record type drives commission splits and portal access.",
    row: "69",
    date: null,
    origin: false,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "recruiting",
    roles: ["agent", "admin"],
    x: 3.4791666666666665,
    y: 26.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 2,
    title: "New recruiting agents assigned to their supervisor",
    description: "New recruiting agents are assigned to a supervisor so the downline is intact before the first referral.",
    row: "74",
    date: null,
    origin: false,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "recruiting",
    roles: ["agent", "admin"],
    x: 6.083333333333333,
    y: 26.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 3,
    title: "Tracked link + QR per recruiter",
    description: "Each recruiter gets a tracked link and QR. Blocked on the owner supplying the 150 recruiter names.",
    row: "55",
    date: "11 Sep",
    origin: true,
    noTake: false,
    status: "pending",
    blocker: "Awaiting the owner's 150 recruiter names",
    lane: "recruiting",
    roles: ["agent", "admin"],
    x: 8.6875,
    y: 26.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 4,
    title: "Submit referral — agent portal",
    description: "Agents submit referrals through the agent portal. The referral is the start of a traceable student record.",
    row: "1, 55",
    date: "11 Sep",
    origin: true,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "recruiting",
    roles: ["agent"],
    x: 11.291666666666666,
    y: 26.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 5,
    title: "Commission attributed to recruiter, down the chain",
    description: "Commission is attributed to the recruiter and walks down the supervisor chain.",
    row: "22",
    date: "11 Sep",
    origin: true,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "recruiting",
    roles: ["agent", "finance"],
    x: 13.895833333333334,
    y: 26.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 6,
    title: "B2B three-way loop",
    description: "A B2B three-way loop between college, employer, and agent. Not in this build; no video take.",
    row: "38",
    date: "11 Sep",
    origin: true,
    noTake: true,
    status: "not-built",
    blocker: null,
    lane: "recruiting",
    roles: ["agent", "admin"],
    x: 16.5,
    y: 26.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 7,
    title: "CRM / Lead Host feed",
    description: "Inbound leads from the CRM / Lead Host feed. Waiting on an API key.",
    row: "54",
    date: "11 Sep",
    origin: true,
    noTake: false,
    status: "pending",
    blocker: "API key pending",
    lane: "ingest",
    roles: ["admissions", "admin"],
    x: 3.4791666666666665,
    y: 23.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 8,
    title: "Google Sheets ingest",
    description: "Spreadsheet ingest from Google Sheets. Waiting on credentials.",
    row: "54",
    date: "11 Sep",
    origin: true,
    noTake: false,
    status: "pending",
    blocker: "Credential pending",
    lane: "ingest",
    roles: ["admissions", "admin"],
    x: 6.083333333333333,
    y: 23.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 9,
    title: "Webhook and CSV ingest (no CRM key)",
    description: "Webhook and CSV ingest that does not require a CRM key. Live fallback for every other source.",
    row: "54, 1",
    date: "11 Sep",
    origin: true,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "ingest",
    roles: ["admissions", "admin"],
    x: 8.6875,
    y: 23.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 10,
    title: "Walk-in, phone, web form, manual paste",
    description: "Walk-in, phone, web form, and manual paste all land in the same enquiry queue.",
    row: "1",
    date: "11 Sep",
    origin: true,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "ingest",
    roles: ["admissions"],
    x: 11.291666666666666,
    y: 23.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 11,
    title: "One traceable record; business vs consumer columns",
    description: "Every enquiry becomes one traceable record, with business and consumer columns kept apart.",
    row: "1, 37",
    date: "11 Sep",
    origin: true,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "ingest",
    roles: ["admissions", "counsellor"],
    x: 13.895833333333334,
    y: 23.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 12,
    title: "Enquiry routed round-robin; queue is time-based",
    description: "Enquiries are routed round-robin. The queue is strictly time-based.",
    row: "2, 11",
    date: "11 Sep",
    origin: true,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "ingest",
    roles: ["admissions"],
    x: 16.5,
    y: 23.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 13,
    title: "Claim — admissions notified; counsellor told",
    description: "On claim, admissions is notified and the counsellor is told. Ownership is explicit.",
    row: "21, 32",
    date: "11 Sep",
    origin: true,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "ingest",
    roles: ["admissions", "counsellor"],
    x: 19.104166666666668,
    y: 23.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 14,
    title: "Sales books the counsellor calendar directly",
    description: "Sales booking the counsellor calendar directly. Not in this build.",
    row: "30",
    date: "11 Sep",
    origin: true,
    noTake: false,
    status: "not-built",
    blocker: null,
    lane: "ingest",
    roles: ["admissions"],
    x: 21.708333333333332,
    y: 23.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 15,
    title: "Convert inquiry to application",
    description: "Convert an inquiry into an application without leaving the record.",
    row: "3, 37",
    date: "11 Sep",
    origin: true,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "counselling",
    roles: ["admissions"],
    x: 16.5,
    y: 21.6875,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 16,
    title: "45-minute booking slots",
    description: "Counselling is booked in 45-minute slots.",
    row: "31",
    date: null,
    origin: false,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "counselling",
    roles: ["counsellor"],
    x: 16.5,
    y: 20.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 17,
    title: "Google Calendar sync",
    description: "Slots push to Google Calendar when sync is enabled.",
    row: "64",
    date: "11 Sep",
    origin: true,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "counselling",
    roles: ["counsellor", "admin"],
    x: 16.5,
    y: 18.6875,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 18,
    title: "Counsellor calendar, past and present",
    description: "Counsellor calendar shows past and present appointments on one surface.",
    row: "29",
    date: "11 Sep",
    origin: true,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "counselling",
    roles: ["counsellor"],
    x: 19.104166666666668,
    y: 20.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 19,
    title: "Appointment vs counselling-booked as two states",
    description: "Appointment and counselling-booked are two distinct states, not one.",
    row: "18",
    date: "11 Sep",
    origin: true,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "counselling",
    roles: ["counsellor"],
    x: 24.3125,
    y: 20.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 20,
    title: "Complete session — enrolled, or written reason",
    description: "A session is completed as enrolled, or with a written reason it was not.",
    row: "18, 65",
    date: "11 Sep",
    origin: true,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "counselling",
    roles: ["counsellor", "admissions"],
    x: 26.916666666666668,
    y: 20.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 21,
    title: "Recorded English interview with ID",
    description: "Recorded English interview with ID. Not in this build; no video take.",
    row: "28",
    date: "11 Sep",
    origin: true,
    noTake: true,
    status: "not-built",
    blocker: null,
    lane: "counselling",
    roles: ["counsellor"],
    x: 32.125,
    y: 20.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 22,
    title: "Agent / BDM / partner skip counselling",
    description: "Agent, BDM, and partner referrals skip counselling and go straight to admissions.",
    row: "39",
    date: "11 Sep",
    origin: true,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "admissions",
    roles: ["agent", "admissions"],
    x: 11.291666666666666,
    y: 17.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 23,
    title: "Course+batch hands the student to admissions automatically",
    description: "Choosing course and batch should hand the student to admissions automatically. Not in this build.",
    row: "39",
    date: "11 Sep",
    origin: true,
    noTake: false,
    status: "not-built",
    blocker: null,
    lane: "admissions",
    roles: ["admissions"],
    x: 13.895833333333334,
    y: 17.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 24,
    title: "Pipeline stage on every admissions row",
    description: "Every admissions row carries a pipeline stage. Nothing sits unlabelled.",
    row: "3",
    date: "11 Sep",
    origin: true,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "admissions",
    roles: ["admissions"],
    x: 19.104166666666668,
    y: 17.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 25,
    title: "Documents tab — verified / pending / rejected",
    description: "Documents tab: verified, pending, or rejected, per file.",
    row: "7",
    date: "11 Sep",
    origin: true,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "admissions",
    roles: ["admissions"],
    x: 21.708333333333332,
    y: 17.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 26,
    title: "Classify every ID type",
    description: "Every identity document is classified by type.",
    row: "20",
    date: "11 Sep",
    origin: true,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "admissions",
    roles: ["admissions"],
    x: 24.3125,
    y: 17.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 27,
    title: "Packet auto-filled from validated details",
    description: "The enrolment packet is auto-filled from already-validated student details.",
    row: "23",
    date: "11 Sep",
    origin: true,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "admissions",
    roles: ["admissions"],
    x: 26.916666666666668,
    y: 17.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 28,
    title: "Send packet for signature, signed copy back",
    description: "Send the packet for signature and receive the signed copy. DocuSeal is still beyond mock.",
    row: "24",
    date: "11 Sep",
    origin: true,
    noTake: false,
    status: "pending",
    blocker: "DocuSeal beyond mock",
    lane: "admissions",
    roles: ["admissions"],
    x: 29.520833333333332,
    y: 17.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 29,
    title: "Enrol + extra lifecycle states",
    description: "Enrol, then extra lifecycle states (defer, withdraw, transfer) sit on the same record.",
    row: "3, 67",
    date: "11 Sep",
    origin: true,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "admissions",
    roles: ["admissions"],
    x: 32.125,
    y: 17.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 30,
    title: "Flag documents expiring before course end",
    description: "Flag any document that expires before the course ends.",
    row: "50",
    date: "11 Sep",
    origin: true,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "admissions",
    roles: ["admissions"],
    x: 24.3125,
    y: 15.6875,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 31,
    title: "Filing documents — who booked / converted / eligibility",
    description: "Filing documents capture who booked, who converted, and eligibility evidence.",
    row: "20, 36",
    date: "11 Sep",
    origin: true,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "admissions",
    roles: ["admissions"],
    x: 26.916666666666668,
    y: 15.6875,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 32,
    title: "Document rules, ID name/DOB/expiry checks, AI read",
    description: "Document rules, ID name/DOB/expiry checks, and AI read. Not in this build; no video take.",
    row: "51, 52, 53, 59",
    date: "11 Sep",
    origin: true,
    noTake: true,
    status: "not-built",
    blocker: null,
    lane: "admissions",
    roles: ["admissions"],
    x: 29.520833333333332,
    y: 15.6875,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 33,
    title: "How each document arrived, on screen",
    description: "Show how each document arrived, on screen. Not in this build; no video take.",
    row: "27, 35",
    date: "11 Sep",
    origin: true,
    noTake: true,
    status: "not-built",
    blocker: null,
    lane: "admissions",
    roles: ["admissions"],
    x: 32.125,
    y: 15.6875,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 34,
    title: "Enrolment gates (ID verified, expiry, SLE, OSAP ON)",
    description: "Enrolment gates: ID verified, expiry, SLE, and OSAP Ontario. All four must pass.",
    row: "7, 23, 24",
    date: "11 Sep",
    origin: true,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "admissions",
    roles: ["admissions"],
    x: 21.708333333333332,
    y: 15.6875,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 35,
    title: "Batch alerts at 80 / 90 / 100% and auto-close",
    description: "Batch alerts fire at 80 / 90 / 100 percent and the intake auto-closes.",
    row: "14",
    date: null,
    origin: false,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "capacity",
    roles: ["admissions", "admin"],
    x: 32.125,
    y: 14.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 36,
    title: "Overflow rolls into next intake at capacity",
    description: "Overflow rolls into the next intake the moment a batch hits capacity.",
    row: "19",
    date: "11 Sep",
    origin: true,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "capacity",
    roles: ["admissions"],
    x: 34.729166666666664,
    y: 14.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 37,
    title: "Placement map to nearest partners",
    description: "Placement map sends the student to the nearest partner.",
    row: "8",
    date: "11 Sep",
    origin: true,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "capacity",
    roles: ["admissions"],
    x: 37.333333333333336,
    y: 14.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 38,
    title: "Placement partners with locations",
    description: "Placement partners are stored with locations, not just names.",
    row: "9",
    date: "11 Sep",
    origin: true,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "capacity",
    roles: ["admissions"],
    x: 39.9375,
    y: 14.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 39,
    title: "Room / resource booking",
    description: "Room and resource booking. Not in this build.",
    row: "71",
    date: null,
    origin: false,
    noTake: false,
    status: "not-built",
    blocker: null,
    lane: "capacity",
    roles: ["admin"],
    x: 37.333333333333336,
    y: 12.6875,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 40,
    title: "Funded vs self-pay desks; funding type routes the role",
    description: "Funded and self-pay sit on separate desks. Funding type routes the role that owns the file.",
    row: "6, 15",
    date: "11 Sep",
    origin: true,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "funding",
    roles: ["finance", "admissions"],
    x: 32.125,
    y: 11.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 41,
    title: "Government funding tracked by hand (ledger)",
    description: "Government funding is tracked by hand in a ledger — no automatic draw yet.",
    row: "26",
    date: "11 Sep",
    origin: true,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "funding",
    roles: ["finance"],
    x: 34.729166666666664,
    y: 11.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 42,
    title: "Two commissions per enrolment",
    description: "Two commissions post per enrolment: recruiter chain plus the other contracted cut.",
    row: "16",
    date: "11 Sep",
    origin: true,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "funding",
    roles: ["finance", "agent"],
    x: 37.333333333333336,
    y: 11.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 43,
    title: "BDM paid a fixed amount per student",
    description: "BDMs are paid a fixed amount per student, not a percentage.",
    row: "68",
    date: "11 Sep",
    origin: true,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "funding",
    roles: ["finance"],
    x: 32.125,
    y: 9.6875,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 44,
    title: "Payroll",
    description: "Payroll. Not in this build.",
    row: "72",
    date: null,
    origin: false,
    noTake: false,
    status: "not-built",
    blocker: null,
    lane: "funding",
    roles: ["finance"],
    x: 37.333333333333336,
    y: 9.6875,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 45,
    title: "Enrol remotely, same rules (public book)",
    description: "Students can enrol remotely under the same rules as a public booking. No video take.",
    row: "25",
    date: "11 Sep",
    origin: true,
    noTake: true,
    status: "live",
    blocker: null,
    lane: "student",
    roles: ["student", "admissions"],
    x: 19.104166666666668,
    y: 8.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 46,
    title: "Upload once, then locked; 26-step checklist (backend)",
    description: "Upload once, then locked. A 26-step checklist runs on the backend.",
    row: "13, 40",
    date: null,
    origin: false,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "student",
    roles: ["student", "admissions"],
    x: 24.3125,
    y: 8.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 47,
    title: "CAS login created at enrolment — set password",
    description: "CAS login is created at enrolment. The student sets the password.",
    row: "41",
    date: null,
    origin: false,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "student",
    roles: ["student", "admin"],
    x: 32.125,
    y: 8.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 48,
    title: "Real email delivery from the college demo mailbox",
    description: "Real email delivery from the college demo mailbox. Waiting on outbound enable.",
    row: "62",
    date: null,
    origin: false,
    noTake: false,
    status: "pending",
    blocker: "Real mailbox / outbound enable",
    lane: "student",
    roles: ["admin"],
    x: 34.729166666666664,
    y: 8.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 49,
    title: "SSO switched on for A1 (Microsoft ID)",
    description: "SSO switched on for A1 against Microsoft ID. Waiting on the live switch-on.",
    row: "61, 41",
    date: null,
    origin: false,
    noTake: false,
    status: "pending",
    blocker: "Live SSO switch-on",
    lane: "student",
    roles: ["admin", "student"],
    x: 37.333333333333336,
    y: 8.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 50,
    title: "Student portal (admissions vs student)",
    description: "Student portal is a different surface from admissions — same record, different eyes.",
    row: "10, 63",
    date: "11 Sep",
    origin: true,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "student",
    roles: ["student", "admissions"],
    x: 39.9375,
    y: 8.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 51,
    title: "Two-way email — sending and receiving replies",
    description: "Two-way email, sending and receiving replies. Not in this build; no video take.",
    row: "33, 57",
    date: "11 Sep",
    origin: true,
    noTake: true,
    status: "not-built",
    blocker: null,
    lane: "student",
    roles: ["admin"],
    x: 34.729166666666664,
    y: 6.6875,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 52,
    title: "Student emailed an upload link with a deadline",
    description: "Student emailed an upload link with a deadline. Not in this build; no video take.",
    row: "66",
    date: "11 Sep",
    origin: true,
    noTake: true,
    status: "not-built",
    blocker: null,
    lane: "student",
    roles: ["student", "admissions"],
    x: 37.333333333333336,
    y: 6.6875,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 53,
    title: "College branding as the look-and-feel",
    description: "College branding is the look-and-feel of every surface, not a skin on login only.",
    row: "75",
    date: null,
    origin: false,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "platform",
    roles: ["admin"],
    x: 3.4791666666666665,
    y: 5.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 54,
    title: "Login page demo picker",
    description: "Login page includes a demo-tenant picker. No video take.",
    row: "44",
    date: null,
    origin: false,
    noTake: true,
    status: "live",
    blocker: null,
    lane: "platform",
    roles: ["admin"],
    x: 6.083333333333333,
    y: 5.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 55,
    title: "Realistic demo numbers",
    description: "Demo numbers are realistic — queues, batches, and money look like a live college.",
    row: "49",
    date: null,
    origin: false,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "platform",
    roles: ["admin"],
    x: 8.6875,
    y: 5.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 56,
    title: "Header Switch role (demo)",
    description: "Header Switch role lets a demo walk every desk without logging out.",
    row: "17",
    date: null,
    origin: false,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "platform",
    roles: ["admin"],
    x: 11.291666666666666,
    y: 5.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 57,
    title: "Role-based views, sensitive fields restricted",
    description: "Role-based views. Sensitive fields are restricted, not just hidden in CSS.",
    row: "4",
    date: "11 Sep",
    origin: true,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "platform",
    roles: ["admin"],
    x: 13.895833333333334,
    y: 5.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 58,
    title: "Departments and divisions on top of roles",
    description: "Departments and divisions sit on top of roles, so two admissions officers can see different campuses.",
    row: "5",
    date: "11 Sep",
    origin: true,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "platform",
    roles: ["admin"],
    x: 16.5,
    y: 5.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 59,
    title: "Four physical campuses",
    description: "Four physical campuses are first-class locations, not a dropdown afterthought.",
    row: "70",
    date: null,
    origin: false,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "platform",
    roles: ["admin"],
    x: 19.104166666666668,
    y: 5.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 60,
    title: "Dangerous delete commands gated",
    description: "Dangerous delete commands are gated. Accidental wipe is a confirmed, role-checked act.",
    row: "46",
    date: null,
    origin: false,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "platform",
    roles: ["admin"],
    x: 21.708333333333332,
    y: 5.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 61,
    title: "Audit trail of who did what",
    description: "Audit trail of who did what, on every mutation that matters.",
    row: "12, 42",
    date: null,
    origin: false,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "platform",
    roles: ["admin"],
    x: 24.3125,
    y: 5.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 62,
    title: "Microsoft SSO (SAML) per college, behind an off switch",
    description: "Microsoft SSO (SAML) per college, behind an off switch until the owner flips it.",
    row: "47",
    date: null,
    origin: false,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "platform",
    roles: ["admin"],
    x: 26.916666666666668,
    y: 5.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 63,
    title: "Reporting module",
    description: "Reporting module covers pipeline, funding, commissions, and batch fill.",
    row: "73",
    date: "11 Sep",
    origin: true,
    noTake: false,
    status: "live",
    blocker: null,
    lane: "platform",
    roles: ["admin", "finance"],
    x: 29.520833333333332,
    y: 5.0625,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 64,
    title: "Internal staff chat",
    description: "Internal staff chat. Not in this build; no video take.",
    row: "34",
    date: "11 Sep",
    origin: true,
    noTake: true,
    status: "not-built",
    blocker: null,
    lane: "backlog",
    roles: ["admin"],
    x: 3.4791666666666665,
    y: 3.6875,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 65,
    title: "Microsoft Teams",
    description: "Microsoft Teams integration. Not in this build; no video take.",
    row: "60",
    date: "11 Sep",
    origin: true,
    noTake: true,
    status: "not-built",
    blocker: null,
    lane: "backlog",
    roles: ["admin"],
    x: 6.083333333333333,
    y: 3.6875,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 66,
    title: "Import existing students",
    description: "Import of existing students. Not in this build; no video take.",
    row: "56",
    date: "11 Sep",
    origin: true,
    noTake: true,
    status: "not-built",
    blocker: null,
    lane: "backlog",
    roles: ["admin", "admissions"],
    x: 8.6875,
    y: 3.6875,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 67,
    title: "Retention 3 y / 1 mo — not built",
    description: "Retention 3 years / 1 month. Not in this build; no video take.",
    row: "43",
    date: "11 Sep",
    origin: true,
    noTake: true,
    status: "not-built",
    blocker: null,
    lane: "backlog",
    roles: ["admin"],
    x: 11.291666666666666,
    y: 3.6875,
    w: 2.375,
    h: 1.125,
  },
  {
    id: 68,
    title: "Export follows your folder structure — not built",
    description: "Export that follows the college folder structure. Not in this build; no video take.",
    row: "58",
    date: "11 Sep",
    origin: true,
    noTake: true,
    status: "not-built",
    blocker: null,
    lane: "backlog",
    roles: ["admin"],
    x: 13.895833333333334,
    y: 3.6875,
    w: 2.375,
    h: 1.125,
  },
];

export const EDGES: Edge[] = [
  { from: 1, to: 2, label: null },
  { from: 2, to: 3, label: null },
  { from: 3, to: 4, label: "/r/:token" },
  { from: 4, to: 22, label: "skip_counselling" },
  { from: 4, to: 5, label: null },
  { from: 22, to: 24, label: "INQUIRY" },
  { from: 7, to: 11, label: "ingest when keyed" },
  { from: 8, to: 11, label: null },
  { from: 9, to: 11, label: null },
  { from: 10, to: 11, label: null },
  { from: 11, to: 12, label: "ingest_lead" },
  { from: 11, to: 15, label: "convert_to_application" },
  { from: 12, to: 13, label: "apply_routing" },
  { from: 13, to: 18, label: null },
  { from: 45, to: 18, label: "book_slot" },
  { from: 16, to: 18, label: "slot required" },
  { from: 16, to: 17, label: "push if enabled" },
  { from: 18, to: 19, label: null },
  { from: 19, to: 20, label: "set_outcome" },
  { from: 20, to: 24, label: "ENROLLED" },
  { from: 15, to: 24, label: "APPLIED" },
  { from: 24, to: 25, label: null },
  { from: 25, to: 34, label: null },
  { from: 25, to: 26, label: null },
  { from: 26, to: 30, label: null },
  { from: 26, to: 31, label: null },
  { from: 34, to: 27, label: null },
  { from: 27, to: 28, label: "DocuSeal" },
  { from: 28, to: 29, label: "signed copy" },
  { from: 24, to: 29, label: "execute_transition" },
  { from: 29, to: 47, label: null },
  { from: 29, to: 40, label: "payment_method" },
  { from: 29, to: 35, label: null },
  { from: 29, to: 42, label: null },
  { from: 29, to: 43, label: "FIXED_AMOUNT" },
  { from: 47, to: 48, label: "stage_outbound" },
  { from: 47, to: 49, label: "Entra staged" },
  { from: 47, to: 50, label: null },
  { from: 50, to: 46, label: null },
  { from: 40, to: 41, label: null },
  { from: 5, to: 42, label: null },
  { from: 35, to: 36, label: "roll_now" },
  { from: 36, to: 37, label: null },
  { from: 37, to: 38, label: null },
  { from: 53, to: 54, label: null },
  { from: 57, to: 58, label: "on top of roles" },
  { from: 57, to: 56, label: null },
  { from: 62, to: 49, label: "owner flips on" },
];

export const JOURNEYS: Journey[] = [
  {
    id: "consumer",
    label: "Walk-in student",
    blurb: "Front desk to portal: claim, counsel, documents, gates, enrol.",
    nodes: [10, 11, 12, 13, 16, 18, 19, 20, 24, 25, 34, 27, 28, 29, 47, 50, 46],
  },
  {
    id: "agent",
    label: "Agent referral",
    blurb: "Tracked link, skip counselling, pipeline, commissions down the chain.",
    nodes: [1, 2, 3, 4, 22, 24, 25, 34, 27, 28, 29, 5, 42],
  },
  {
    id: "remote",
    label: "Remote enrol",
    blurb: "Public book under the same rules, then a CAS login and the student desk.",
    nodes: [45, 18, 19, 20, 24, 25, 34, 27, 28, 29, 47, 50, 46],
  },
  {
    id: "capacity",
    label: "Batch to placement",
    blurb: "Enrol fills a batch, overflow rolls, nearest partner is mapped.",
    nodes: [29, 35, 36, 37, 38],
  },
];

export const PAGE = { width: 44.583333333333336, height: 29.166666666666668 };

export const BY_ID: Record<number, Capability> = Object.fromEntries(
  CAPABILITIES.map((c) => [c.id, c]),
);

export function neighbors(id: number) {
  const upstream = EDGES.filter((e) => e.to === id);
  const downstream = EDGES.filter((e) => e.from === id);
  return { upstream, downstream };
}

export function coverage() {
  const live = CAPABILITIES.filter((c) => c.status === "live").length;
  const pending = CAPABILITIES.filter((c) => c.status === "pending").length;
  const notBuilt = CAPABILITIES.filter((c) => c.status === "not-built").length;
  const origin = CAPABILITIES.filter((c) => c.origin).length;
  const noTake = CAPABILITIES.filter((c) => c.noTake).length;
  return { total: CAPABILITIES.length, live, pending, notBuilt, origin, noTake };
}

